version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m0a8g7b6
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t node:latest .
      - docker tag node:latest public.ecr.aws/m0a8g7b6/ecr-repo:latest     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/m0a8g7b6/ecr-repo:latest
