version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - AWS_DEFAULT_REGION=us-east-1 
      - AWS_ACCOUNT_ID=383633643106
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 383633643106.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=383633643106.dkr.ecr.us-east-1.amazonaws.com/first-ecr
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"node-container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
